simple_ardop:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  shoulder_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  bicep_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: bicep_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  forearm_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: forearm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wrist_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wrist2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wrist3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  end_effector_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: end_effector_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_front_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_front_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_front_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_front_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_back_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_back_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_back_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_back_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
