simple_ardop:
  
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder_joint
      - bicep_joint
      - forearm_joint
      - wrist_joint
      - wrist2_joint
      - wrist3_joint
    gains:
      shoulder_joint: {p: 100.0, i: 0.01, d: 10.0}
      bicep_joint: {p: 100.0, i: 0.01, d: 10.0}
      forearm_joint: {p: 100.0, i: 0.01, d: 10.0}
      wrist_joint: {p: 100.0, i: 0.01, d: 10.0}
      wrist2_joint: {p: 100.0, i: 0.01, d: 10.0}
      wrist3_joint: {p: 100.0, i: 0.01, d: 10.0}

  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - end_effector_joint
    gains:
      end_effector_joint: {p: 100.0, i: 0.01, d: 10.0}

  chassis_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - wheel_front_left_joint
      - wheel_front_right_joint
      - wheel_back_left_joint
      - wheel_back_right_joint   
    gains:
      wheel_front_left_joint: {p: 100.0, i: 0.01, d: 10.0}
      wheel_front_right_joint: {p: 100.0, i: 0.01, d: 10.0}
      wheel_back_left_joint: {p: 100.0, i: 0.01, d: 10.0}
      wheel_back_right_joint: {p: 100.0, i: 0.01, d: 10.0}
